version: '3'

services:
  lsabermgt:
    image: jon/lsabermgt
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - "MQTT_USER=${MQTTUser}"
      - "MQTT_PASSWD=${MQTTPasswd}"
      - "MQTT_HOST=${MQTTServ}"
      - "MQTT_PORT=${MQTTPort}"
      - "LOGLEVEL=${LOGLEVEL}"
    ports:
     - "2080:8080"

      
